python track_vot23.py squirrel
python track_vot23.py stripedfish
python track_vot23.py surfboard-12
python track_vot23.py tank-16
python track_vot23.py tank-9
python track_vot23.py tennis
python track_vot23.py tiger-4
python track_vot23.py train-7
python track_vot23.py transparent_fish
python track_vot23.py uav1
python track_vot23.py umbrella-19
python track_vot23.py umbrella-9
python track_vot23.py volleyball
python track_vot23.py volleyball-18
python track_vot23.py volleyball-19
python track_vot23.py whitefish
python track_vot23.py wiper
python track_vot23.py wubble_bubble
python track_vot23.py yoyo-7
python track_vot23.py zebra-10
python track_vot23.py zebra-16
python track_vot23.py zebrafish1